p8105_hw2_SZ3319
================
Shiyu Zhang
2024-09-30

## Problem 1

### 1.1 Import the dataset and clean names

``` r
transit_df = 
  read_csv("hw2data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", na = c("NA", "", ".")) |> 
  janitor::clean_names()

tail(transit_df, 10)
```

    ## # A tibble: 10 × 32
    ##    division line   station_name station_latitude station_longitude route1 route2
    ##    <chr>    <chr>  <chr>                   <dbl>             <dbl> <chr>  <chr> 
    ##  1 IRT      White… Simpson St               40.8             -73.9 2      5     
    ##  2 IRT      White… Simpson St               40.8             -73.9 2      5     
    ##  3 IRT      White… Simpson St               40.8             -73.9 2      5     
    ##  4 IRT      White… Simpson St               40.8             -73.9 2      5     
    ##  5 IRT      White… Simpson St               40.8             -73.9 2      5     
    ##  6 IRT      White… Wakefield-2…             40.9             -73.9 2      5     
    ##  7 IRT      White… Wakefield-2…             40.9             -73.9 2      5     
    ##  8 IRT      White… Wakefield-2…             40.9             -73.9 2      5     
    ##  9 IRT      Flush… 34 St Hudso…             40.8             -74.0 7      <NA>  
    ## 10 IRT      Flush… 34 St Hudso…             40.8             -74.0 7      <NA>  
    ## # ℹ 25 more variables: route3 <chr>, route4 <chr>, route5 <chr>, route6 <chr>,
    ## #   route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>,
    ## #   entrance_type <chr>, entry <chr>, exit_only <chr>, vending <chr>,
    ## #   staffing <chr>, staff_hours <chr>, ada <lgl>, ada_notes <chr>,
    ## #   free_crossover <lgl>, north_south_street <chr>, east_west_street <chr>,
    ## #   corner <chr>, entrance_latitude <dbl>, entrance_longitude <dbl>,
    ## #   station_location <chr>, entrance_location <chr>

### 1.2 Select variables

Select columns and clean the data; convert `entry` to logical.

``` r
transit_select <- transit_df |> 
  select(
    line, 
    station_name, 
    station_latitude, 
    station_longitude, 
    starts_with("route"), 
    entry, 
    vending, 
    entrance_type, 
    ada) |> 
  mutate(
    entry = ifelse(entry == "YES", TRUE, FALSE)
    )
```

Description:

### 1.3 Analysis the data

#### 1.3.1 Calculate the distinct station.

``` r
distinct_stations <- transit_select |> 
  distinct(line, station_name) |> 
  nrow()

distinct_stations
```

    ## [1] 465

There are **465** distinct stations are there.

#### 1.3.2 Calculate the number of ADA compliant.

``` r
ADA_compliant_stations <- 
  transit_select |> 
  filter(ada == "TRUE") |> 
  distinct(line, station_name) |> 
  nrow()

ADA_compliant_stations
```

    ## [1] 84

There are **84** ADA compliant stations.

#### 1.3.3 Propotion of station

Calculate the total number of stations without vending.

``` r
no_vending <- transit_select |> 
  filter(vending == "NO") |>
  nrow()
```

Calculate how many of them allow entry.

``` r
allow_entry_no_vending <- transit_select |> 
  filter(vending == "NO", entry == TRUE) |>
  nrow()
```

Calculate the proportion.

``` r
proportion_no_vending <-
  allow_entry_no_vending / no_vending

proportion_no_vending
```

    ## [1] 0.3770492

The proportion of station entrances without vending allow entrance is
**0.3770492**.

### 1.4 Reform the data.

## Problem 2

### 2.1 Import the `Mr. Trash Wheel` sheet and clean names

``` r
mr_df = 
  read_excel("hw2data/202409 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", skip = 1) |> 
  janitor::clean_names()

head(mr_df, 10)
```

    ## # A tibble: 10 × 16
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 10 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>, x15 <lgl>,
    ## #   x16 <lgl>

``` r
mr_clean =
  mr_df |> 
  select(dumpster:homes_powered) |> 
  drop_na(dumpster) |> #omit rows that do not include dumpster-specific data
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    year = as.numeric(year),
    trash_wheel = "Mr"
  ) # round the number of sports balls to the nearest integer and converts the result to an integer variable (using as.integer)

tail(mr_clean, 10)
```

    ## # A tibble: 10 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1      642 April  2024 2024-04-04 00:00:00        4.3                  15
    ##  2      643 April  2024 2024-04-09 00:00:00        3.49                 15
    ##  3      644 April  2024 2024-04-09 00:00:00        1.25                 15
    ##  4      645 May    2024 2024-05-02 00:00:00        4.9                  15
    ##  5      646 May    2024 2024-05-10 00:00:00        3.68                 15
    ##  6      647 May    2024 2024-05-10 00:00:00        4.7                  15
    ##  7      648 May    2024 2024-05-30 00:00:00        4.13                 15
    ##  8      649 May    2024 2024-05-30 00:00:00        3.34                 15
    ##  9      650 June   2024 2024-06-11 00:00:00        3.02                 15
    ## 10      651 June   2024 2024-06-11 00:00:00        4                    15
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

### 2.2 Import the `Professor Trash Wheel` sheet and clean names

``` r
professor_df = 
  read_excel("hw2data/202409 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1) |> 
  janitor::clean_names()

head(professor_df, 10)
```

    ## # A tibble: 10 × 13
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

``` r
professor_clean =
  professor_df |> 
  select(dumpster:homes_powered) |> 
  drop_na(dumpster, month) |> #omit rows that do not include dumpster-specific data
  mutate(trash_wheel = "Professor")
  

tail(professor_clean, 10)
```

    ## # A tibble: 10 × 14
    ##    dumpster month      year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>     <dbl> <dttm>                    <dbl>              <dbl>
    ##  1      109 August     2023 2023-08-09 00:00:00        2.64                 15
    ##  2      110 August     2023 2023-08-23 00:00:00        2.82                 15
    ##  3      111 September  2023 2023-09-06 00:00:00        1.71                 10
    ##  4      112 September  2023 2023-09-26 00:00:00        2.43                 15
    ##  5      113 October    2023 2023-10-27 00:00:00        1.28                 10
    ##  6      114 December   2023 2023-12-05 00:00:00        2.13                 15
    ##  7      115 January    2024 2024-01-08 00:00:00        2.2                  15
    ##  8      116 March      2024 2024-03-14 00:00:00        3.75                 15
    ##  9      117 April      2024 2024-04-16 00:00:00        3                    15
    ## 10      118 May        2024 2024-05-30 00:00:00        2.48                 15
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, trash_wheel <chr>

### 2.3 Import the `Gwynnda Trash Wheel` sheet and clean names

``` r
gwynnda_df = 
  read_excel("hw2data/202409 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", skip = 1) |> 
  janitor::clean_names()

head(gwynnda_df, 10)
```

    ## # A tibble: 10 × 12
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

``` r
gwynnda_clean =
  gwynnda_df |> 
  select(dumpster:homes_powered) |> 
  drop_na(dumpster) |> 
  mutate(trash_wheel = "Gwynnda")

tail(gwynnda_clean, 10)
```

    ## # A tibble: 10 × 13
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1      253 April  2024 2024-04-05 00:00:00        3.43                 15
    ##  2      254 April  2024 2024-04-26 00:00:00        2.87                 15
    ##  3      255 May    2024 2024-05-14 00:00:00        3.27                 15
    ##  4      256 May    2024 2024-05-29 00:00:00        2.72                 15
    ##  5      257 May    2024 2024-05-29 00:00:00        3                    15
    ##  6      258 May    2024 2024-05-29 00:00:00        3.78                 15
    ##  7      259 May    2024 2024-05-30 00:00:00        3.35                 15
    ##  8      260 May    2024 2024-05-31 00:00:00        3.55                 15
    ##  9      261 June   2024 2024-06-01 00:00:00        2.88                 15
    ## 10      262 June   2024 2024-06-07 00:00:00        3.43                 15
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

### 2.4 Bind the datasets

``` r
bind_data = 
  bind_rows(mr_clean, professor_clean, gwynnda_clean) |>
  janitor::clean_names() |>
  select(trash_wheel, everything()) 

head(bind_data, 10)
```

    ## # A tibble: 10 × 15
    ##    trash_wheel dumpster month  year date                weight_tons
    ##    <chr>          <dbl> <chr> <dbl> <dttm>                    <dbl>
    ##  1 Mr                 1 May    2014 2014-05-16 00:00:00        4.31
    ##  2 Mr                 2 May    2014 2014-05-16 00:00:00        2.74
    ##  3 Mr                 3 May    2014 2014-05-16 00:00:00        3.45
    ##  4 Mr                 4 May    2014 2014-05-17 00:00:00        3.1 
    ##  5 Mr                 5 May    2014 2014-05-17 00:00:00        4.06
    ##  6 Mr                 6 May    2014 2014-05-20 00:00:00        2.71
    ##  7 Mr                 7 May    2014 2014-05-21 00:00:00        1.91
    ##  8 Mr                 8 May    2014 2014-05-28 00:00:00        3.7 
    ##  9 Mr                 9 June   2014 2014-06-05 00:00:00        2.52
    ## 10 Mr                10 June   2014 2014-06-11 00:00:00        3.76
    ## # ℹ 9 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

### 2.5 Total description

``` r
total_weight_professor =
  bind_data |> 
  filter(trash_wheel == "Professor") |> 
  summarise(total_weight = sum(weight_tons, na.rm = TRUE)) |> 
  pull(total_weight)

total_weight_professor
```

    ## [1] 246.74

``` r
total_cigarette_butts_gwynnda =
  bind_data |> 
  filter(trash_wheel == "Gwynnda" & year == 2022 & month == "June") |> 
  summarise(
    total_cigarette_butts = sum(cigarette_butts, na.rm = TRUE)
  ) |> 
  pull(total_cigarette_butts)

total_cigarette_butts_gwynnda
```

    ## [1] 18120

## Problem 3

### 3.1 Import data and clean names

Import the data and clean names.

``` r
baker_df = 
  read_csv("hw2data/gbb_datasets/bakers.csv") |> 
  janitor::clean_names()
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
bake_df =
  read_csv("hw2data/gbb_datasets/bakes.csv") |> 
  janitor::clean_names()
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
result_df = 
  read_csv("hw2data/gbb_datasets/results.csv", skip = 2) |> 
  janitor::clean_names()
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
viewer_df =
  read_csv("hw2data/gbb_datasets/viewers.csv") |> 
  janitor::clean_names()
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**bakers**: Separate the bakers’ name in `bakers` dataset.

``` r
baker_clean = 
  baker_df |> 
  separate("baker_name", into = c("baker", "last_name"), sep = " ") |> 
  distinct() 
```

**bakes**: Exchange `Jo` to `"Jo"`.

``` r
bake_clean = 
  bake_df |> 
  distinct() |> 
  mutate(baker = ifelse(baker ==  '"Jo"', "Jo", baker))
```

### 3.2 Set up a dataset combined with data from `bakers.csv`, `bakes.csv`, `results.csv`.

Check if all bakers are there in `bake_clean`, `result_df` and
`baker_clean`.

``` r
ms1_data = anti_join(result_df, baker_clean, by = "baker")

ms1_data
```

    ## # A tibble: 8 × 5
    ##   series episode baker  technical result    
    ##    <dbl>   <dbl> <chr>      <dbl> <chr>     
    ## 1      2       1 Joanne        11 IN        
    ## 2      2       2 Joanne        10 IN        
    ## 3      2       3 Joanne         1 IN        
    ## 4      2       4 Joanne         8 IN        
    ## 5      2       5 Joanne         6 IN        
    ## 6      2       6 Joanne         1 STAR BAKER
    ## 7      2       7 Joanne         3 IN        
    ## 8      2       8 Joanne         1 WINNER

Joanne is shown in `result`, but not in `bakers`.

``` r
ms2_data = anti_join(
  bake_clean, baker_clean,
  by = c("baker"))

ms2_data
```

    ## # A tibble: 0 × 5
    ## # ℹ 5 variables: series <dbl>, episode <dbl>, baker <chr>,
    ## #   signature_bake <chr>, show_stopper <chr>

All bakers in `bake` are shown in `baker`.

Combine the datasets.

``` r
combined_df = 
  baker_clean |> 
  left_join(bake_clean, 
            by = c("baker", "series")) |> 
  left_join(result_df, 
            by = c("baker", "series", "episode")) |> 
  select(-(last_name)) |> 
  arrange(series, episode, technical) |> 
  select(series, episode, baker, everything())
```

### 3.3 Export the `combined_df`.

``` r
write_csv(combined_df,
          "hw2data/gbb_datasets/combined_df.csv")
```

The final `combined_df` dataset has **573** observations and **10**
variables.

### 3.4 Table for readers
